### ISSUE TITLE
Error in Magento 1.9.3.8

### ISSUE THREAD

**Issue by Drifti** [sprankhub/bank-integration#12]
The processed orders get the status like choosen in the configuration, tested "processing" and "complete".
But the state ist wrong, not changed
The order is not payed
The invoice gets payed
  
Any action with changing orders leads to an error like this:

a:5:{i:0;s:155:"Cannot send headers; headers already sent in /usr/www/users/magento/app/code/community/Kinento/Bankintegration/Block/Bind/Main/Grid.php, line 1";i:1;s:1306:"#0 /usr/www/users/magento/lib/Zend/Controller/Response/Abstract.php(148): Zend_Controller_Response_Abstract->canSendHeaders(true)
#1 /usr/www/users/magento/app/code/core/Mage/Core/Controller/Response/Http.php(107): Zend_Controller_Response_Abstract->setRedirect('https://www....', 302)
#2 /usr/www/users/magento/app/code/community/Kinento/Bankintegration/controllers/BindController.php(348): Mage_Core_Controller_Response_Http->setRedirect('https://www....')
#3 /usr/www/users/magento/app/code/core/Mage/Core/Controller/Varien/Action.php(418): Kinento_Bankintegration_BindController->coupleAction()
#4 /usr/www/users/magento/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('couple')
#5 /usr/www/users/magento/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#6 /usr/www/users/magento/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#7 /usr/www/users/magento/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#8 /usr/www/users/magento/index.php(87): Mage::run('', 'store')
#9 {main}";s:3:"url";s:76:"/index.php/bankintegration/bind/couple/key/ef0cf6740cd892d765uz4dccc61b9o5e/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

**Comment by sprankhub** [comment]
To be honest, this version of the extension is unsupported (and I just added a note in the README since we did not communicate this until now). We massively refactored the extension and wanted to sell the "new" version. Unfortunately, we did not succeed in preparing it for selling. Some customers bought it directly from us and use it in production, but it is not available somewhere yet. Feel free to [contact me privately](https://www.simonsprankel.de/) if you are interested in buying the new version.
